version: "3.8"

name: stacks-local

networks:
  default:
    name: stacks-local
    driver: bridge

services:
  # ----------------------------------------------------------------------------
  # Bitcoin regtest node
  # ----------------------------------------------------------------------------

  # Bitcoin regtest node
  bitcoin-node:
    user: bitcoin
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        BITCOIN_VERSION: ${BITCOIN_VERSION}
      target: bitcoind
    image: stacks.local/bitcoin-node
    ports:
      - "18443:18443"
      - "18444:18444"
    volumes:
      - ./conf/bitcoin-runtime.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./conf/wallet.dat:/bitcoin/wallet.dat
      - ./conf/bitcoin-entrypoint.sh:/bitcoin/entrypoint.sh
  
  # ----------------------------------------------------------------------------
  # Stacks base image
  # ----------------------------------------------------------------------------

  # Base image containing both 2.4 and nakamoto `stacks-node` binaries
  stacks-node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BITCOIN_VERSION: ${BITCOIN_VERSION}
        STACKS_2_4_TAG_BRANCH: ${STACKS_2_4_TAG_BRANCH}
        STACKS_NAKAMOTO_TAG_BRANCH: ${STACKS_NAKAMOTO_TAG_BRANCH}
      target: stacks-node
    image: stacks.local/stacks-node
    entrypoint: /bin/bash -c exit
  
  # ----------------------------------------------------------------------------
  # 2.4 nodes
  # ----------------------------------------------------------------------------

  # Leader node
  stacks-2.4-leader-node:
    user: stacks
    image: stacks.local/stacks-node
    env_file:
      - ./conf/stacks.env
    depends_on:
      - bitcoin-node
      - stacks-node
    ports:
      - "5000-5009:20443"
      - "5010-5019:20444"
    environment:
      LEADER: true
      NODE_VERSION: 2.4
    volumes:
      - ./conf/bitcoin-runtime.conf:/home/stacks/.bitcoin/bitcoin.conf

  # Follower nodes
  stacks-2.4-follower-node:
    user: stacks
    image: stacks.local/stacks-node
    env_file:
      - ./conf/stacks.env
    deploy:
      replicas: 2
    depends_on:
      - stacks-2.4-leader-node
    ports:
      - "5020-5029:20443"
      - "5030-5039:20444"
    environment:
      NODE_VERSION: "2.4"

  # ----------------------------------------------------------------------------
  # Nakamoto nodes
  # ----------------------------------------------------------------------------

  # Leader node
  stacks-naka-leader-node:
    user: stacks
    image: stacks.local/stacks-node
    env_file:
      - ./conf/stacks.env
    depends_on:
      - stacks-2.4-leader-node
      - bitcoin-node
      - stacks-node
    ports:
      - "5000-5009:20443"
      - "5010-5019:20444"
    environment:
      LEADER: true
      NODE_VERSION: nakamoto
    volumes:
      - ./conf/bitcoin-runtime.conf:/home/stacks/.bitcoin/bitcoin.conf

  # Follower nodes
  stacks-naka-follower-node:
    user: stacks
    image: stacks.local/stacks-node
    env_file:
      - ./conf/stacks.env
    deploy:
      replicas: 2
    depends_on:
      - stacks-2.4-leader-node
    ports:
      - "5020-5029:20443"
      - "5030-5039:20444"
    environment:
      NODE_VERSION: nakamoto

  # Signer nodes
  # stacks-signer:
  #   user: stacks
  #   image: stacks.local/stacks-node
  #   env_file:
  #     - ./conf/stacks.env
  #   deploy:
  #     replicas: 3
  #   depends_on:
  #     - stacks-naka-leader-node
  #   ports:
  #     - "5040-5049:20443"
  #     - "5050-5059:20444"
  #     - "5060-5069:30002"
  #   environment:
  #     NODE_VERSION: nakamoto

  