version: "3.8"

name: local

networks:
  default:
    name: stacks-local
    driver: bridge

services:

  # ----------------------------------------------------------------------------
  # General environment node (just used to keep labels etc.)
  # ----------------------------------------------------------------------------

  # General environment node
  environment:
    image: busybox:latest
    labels:
      local.stacks.environment_id: "${REGTEST_ENV_ID}"
      local.stacks.role: environment
    entrypoint: "/bin/sh -c 'while : ; do sleep 5; done'"

  # Clarinet
  clarinet:
    user: stacks
    build:
      context: .
      dockerfile: Dockerfile
      target: clarinet
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    image: stacks.local/clarinet
    labels:
      local.stacks.environment_id: "${REGTEST_ENV_ID}"
      local.stacks.role: clarinet

  # ----------------------------------------------------------------------------
  # Bitcoin regtest node
  # ----------------------------------------------------------------------------

  # Bitcoin regtest node
  bitcoin-node:
    user: bitcoin
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        BITCOIN_VERSION: ${BITCOIN_VERSION}
      target: bitcoind
    image: stacks.local/bitcoin-node
    depends_on:
      - environment
    labels:
      local.stacks.environment_id: "${REGTEST_ENV_ID}"
      local.stacks.role: bitcoind
    environment:
      BITCOIN_INITIAL_BLOCKS: ${BITCOIN_INITIAL_BLOCKS}
    ports:
      - "18443:18443"
      - "18444:18444"
    volumes:
      - ./assets/bitcoin-runtime.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./assets/bitcoin-entrypoint.sh:/bitcoin/entrypoint.sh
      - ./environments/${REGTEST_ENV_ID}/logs:/bitcoin/logs/:rw
  
  # ----------------------------------------------------------------------------
  # Stacks base image
  # ----------------------------------------------------------------------------

  # This image is not intended to be run directly, but rather used as a base for
  # the 2.4 and nakamoto nodes. This just helps to keep the service definitions 
  # a little bit cleaner since we don't need to build for each node type.
  stacks-node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BITCOIN_VERSION: ${BITCOIN_VERSION}
        STACKS_2_4_TAG_BRANCH: ${STACKS_2_4_TAG_BRANCH}
        STACKS_NAKAMOTO_TAG_BRANCH: ${STACKS_NAKAMOTO_TAG_BRANCH}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      target: stacks-node
    image: stacks.local/stacks-node
    entrypoint: /bin/bash -c exit

  # Container for building/gathering required binaries
  stacks-build:
    build:
      dockerfile: Dockerfile
      target: build-base
    image: stacks.local/build
    entrypoint: /entrypoint.sh
    environment:
      BITCOIN_VERSION: ${BITCOIN_VERSION}
      STACKS_2_4_TAG_BRANCH: ${STACKS_2_4_TAG_BRANCH}
      STACKS_NAKAMOTO_TAG_BRANCH: ${STACKS_NAKAMOTO_TAG_BRANCH}
    volumes:
      - ./assets/stacks-build-entrypoint.sh:/entrypoint.sh
      - ~/.stacks-regtest/bin:/stacks/bin/:rw
  
  # ----------------------------------------------------------------------------
  # 2.4 nodes
  # ----------------------------------------------------------------------------

  # Leader node
  stacks-2.4-leader-node:
    user: stacks
    image: stacks.local/stacks-node
    labels:
      local.stacks.environment_id: "${REGTEST_ENV_ID}"
      local.stacks.node_version: 2.4
      local.stacks.leader: true
      local.stacks.role: node
    env_file:
      - ./assets/stacks.env
    depends_on:
      - bitcoin-node
      - stacks-node
      - environment
    ports:
      - "5000-5009:20443"
      - "5010-5019:20444"
    environment:
      LEADER: true
      NODE_VERSION: 2.4
    volumes:
      # Load configuration and shellscripts
      - ./assets/bitcoin-runtime.conf:/home/stacks/.bitcoin/bitcoin.conf
      - ./assets/stacks-node-entrypoint.sh:/stacks/bin/entrypoint.sh
      - ./assets/stacks-node-entrypoint-lib.sh:/stacks/bin/stacks-node-entrypoint-lib.sh
      - ./assets/stacks-leader-conf.toml:/stacks/conf/stacks-node.toml
      # Map logs to the container's local environment logs directory
      - ./environments/${REGTEST_ENV_ID}/logs:/stacks/logs/:rw

  # Follower nodes
  stacks-2.4-follower-node:
    user: stacks
    image: stacks.local/stacks-node
    env_file:
      - ./assets/stacks.env
    deploy:
      replicas: 2
    labels:
      local.stacks.environment_id: "${REGTEST_ENV_ID}"
      local.stacks.node_version: 2.4
      local.stacks.leader: false
      local.stacks.role: node
    depends_on:
      - stacks-2.4-leader-node
      - environment
    ports:
      - "5020-5029:20443"
      - "5030-5039:20444"
    environment:
      NODE_VERSION: "2.4"
    volumes:
      # Load configuration and shellscripts
      - ./assets/bitcoin-runtime.conf:/home/stacks/.bitcoin/bitcoin.conf
      - ./assets/stacks-node-entrypoint.sh:/stacks/bin/entrypoint.sh
      - ./assets/stacks-node-entrypoint-lib.sh:/stacks/bin/entrypoint-lib.sh
      - ./assets/stacks-follower-conf.toml:/stacks/conf/stacks-node.toml
      # Map logs to the container's local environment logs directory
      - ./environments/${REGTEST_ENV_ID}/logs:/stacks/logs/:rw

  # ----------------------------------------------------------------------------
  # Nakamoto nodes
  # ----------------------------------------------------------------------------

  # Leader node
  stacks-naka-leader-node:
    user: stacks
    image: stacks.local/stacks-node
    labels:
      local.stacks.environment_id: "${REGTEST_ENV_ID}"
      local.stacks.node_version: nakamoto
      local.stacks.leader: true
      local.stacks.role: node
    env_file:
      - ./assets/stacks.env
    depends_on:
      - stacks-2.4-leader-node
      - bitcoin-node
      - stacks-node
      - environment
    ports:
      - "5000-5009:20443"
      - "5010-5019:20444"
    environment:
      LEADER: true
      NODE_VERSION: nakamoto
    volumes:
      # Load configuration and shellscripts
      - ./assets/bitcoin-runtime.conf:/home/stacks/.bitcoin/bitcoin.conf
      - ./assets/stacks-node-entrypoint.sh:/stacks/bin/entrypoint.sh
      - ./assets/stacks-node-entrypoint-lib.sh:/stacks/bin/entrypoint-lib.sh
      - ./assets/stacks-leader-conf.toml:/stacks/conf/stacks-node.toml
      # Map logs to the container's local environment logs directory
      - ./environments/${REGTEST_ENV_ID}/logs:/stacks/logs/:rw

  # Follower nodes
  stacks-naka-follower-node:
    user: stacks
    image: stacks.local/stacks-node
    env_file:
      - ./assets/stacks.env
    deploy:
      replicas: 2
    labels:
      local.stacks.environment_id: "${REGTEST_ENV_ID}"
      local.stacks.node_version: nakamoto
      local.stacks.leader: false
      local.stacks.role: node
    depends_on:
      - stacks-2.4-leader-node
      - environment
    ports:
      - "5020-5029:20443"
      - "5030-5039:20444"
    environment:
      NODE_VERSION: nakamoto
    volumes:
      # Load configuration and shellscripts
      - ./assets/bitcoin-runtime.conf:/home/stacks/.bitcoin/bitcoin.conf
      - ./assets/stacks-node-entrypoint.sh:/stacks/bin/entrypoint.sh
      - ./assets/stacks-node-entrypoint-lib.sh:/stacks/bin/entrypoint-lib.sh
      - ./assets/stacks-follower-conf.toml:/stacks/conf/stacks-node.toml
      # Map logs to the container's local environment logs directory
      - ./environments/${REGTEST_ENV_ID}/logs:/stacks/logs/:rw

  # Signer nodes
  stacks-signer:
    user: stacks
    image: stacks.local/stacks-node
    env_file:
      - ./assets/stacks.env
    deploy:
      replicas: 3
    labels:
      local.stacks.environment_id: "${REGTEST_ENV_ID}"
      local.stacks.role: signer
    depends_on:
      - stacks-naka-leader-node
      - environment
    ports:
      - "5040-5049:20443"
      - "5050-5059:20444"
      - "5060-5069:30002"
    environment:
      NODE_VERSION: nakamoto
    volumes:
      # Load configuration and shellscripts
      - ./assets/bitcoin-runtime.conf:/home/stacks/.bitcoin/bitcoin.conf
      - ./assets/stacks-node-entrypoint.sh:/stacks/bin/entrypoint.sh
      - ./assets/stacks-node-entrypoint-lib.sh:/stacks/bin/entrypoint-lib.sh
      - ./assets/stacks-signer-conf.toml:/stacks/conf/stacks-signer.toml
      # Map logs to the container's local environment logs directory
      - ./environments/${REGTEST_ENV_ID}/logs:/stacks/logs/:rw

  